### ISSUE TITLE
Value of liftime support isn't calculated correctly

### ISSUE THREAD

**Issue by tsjdev-apps** [medialesson/doki-uwp#1]
If I tap on a user to see the lifetime support only the values of the correspoding month is displayed. It should be caluclated over all months.

![wp_ss_20181219_0001](https://user-images.githubusercontent.com/19834782/50226511-a556ea00-03a3-11e9-9f1e-c890d9833085.png)

**Comment by ginomessmer** [comment]
Fixed in 3955878.
